# ls-rescue
* Download this tool 
  * save your ls before and after your mistake to 2 separate files
  * run `python3 ls-rescue.py -f ls1_file ls2_file`.
* run `python3 ls-rescue.py`
  * input first ls output
  * input second ls output
  
  You'll see what changed.
